Preserve data
Rebelzob/catalog-of-my-things pull request #54
Opened 2023-10-19 20:17 UTC by diarisdiakite

In this PR, I added unit tests for all implemented methods (issue https://github.com/Rebelzob/catalog-of-my-things/issues/34):
📃 For the methods in the Source class
✔️ initialize source
✔️ add_a_source method
✔️ list_all_sources method
✔️ find_source_by_index
✔️ add_item
📃 For the methods in the Movie class
✔️ initialize
✔️ add_a_movie
✔️ find_movie_by_index
✔️ can_be_archived
📃 Added a UI for the Movie and Source options with the following ones available (issue https://github.com/Rebelzob/catalog-of-my-things/issues/35)
✔️ List all movies
✔️ List all sources (e.g. 'From a friend', 'Online shop')
✔️ Add a movie
📃 Created a schema.sql file with tables that is analogical to the structure of the classes that I created (issue https://github.com/Rebelzob/catalog-of-my-things/issues/30, issue https://github.com/Rebelzob/catalog-of-my-things/issues/31 and Issue https://github.com/Rebelzob/catalog-of-my-things/issues/37)
✔️ movies table (add all properties and associations from the parent Item class as table columns)
✔️ sources table
📃 Created files to preserve_data files (issue #36)
✔️ created a save_data and a load_data for the movie class instances
✔️ created a save_data and a load_data files for the source class instances
✔️ save all the data in json files.

2023-10-19 21:02 UTC, kambereBr requested changes
STATUS : CHANGE REQUIRED ♻️ 

Hey @diarisdiakite, 
Good job so far! Please check comments and try to apply if possible.

Happy coding !

2023-10-19 21:02 UTC, kambereBr commented on app/spec/movie_spec.rb
> +    movie = Movie.new('Titanic', 'Youtube', '1997-12-31', true, true)
Once, Movie class refactored, please make sure to update parameters in this file as well. That way, all unit tests pass

2023-10-20 06:08 UTC, diarisdiakite commented on app/models/movie.rb
> +  def initialize(_title, _source, _publish_date, _archived, silent)
@kambereBr Updated. Thanks for the review.

2023-10-20 06:09 UTC, diarisdiakite commented on app/spec/movie_spec.rb
> +    movie = Movie.new('Titanic', 'Youtube', '1997-12-31', true, true)
Updated @kambereBr. Thanks for the review and for your help.

2023-10-20 15:34 UTC, merged