Ruby Capstone Project
Rebelzob/catalog-of-my-things pull request #61
Opened 2023-10-20 18:53 UTC by JavierAybar

# **_`Catalog of my things`_** 📚 🎶 🎮 🎥 

**_members of this project_**:

- **_Javier Aybar_** [GitHub](https://github.com/JavierAybar)
- **_Bruno Kambere_** [GitHub](https://github.com/kambereBr)
- **_Karim Barragan_** [GitHub](https://github.com/Rebelzob)
- **_Diariatou Diakite_** [GitHub](https://github.com/diarisdiakite)

**_In this project we did:_**

✅  **_Create a console app that will help you to keep a record of different types of things you own:( `books`, `music albums`, `movies`, and `games`)_**

✅ **_Everything will be based on the UML class diagram_**

✅ **_The data stored in JSON files_**

### **_You can see the project requiremets in the following links:_**
https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md

2023-10-20 21:22 UTC, Owusu-Desmond requested changes
Hi @kambereBr @diarisdiakite @Rebelzob and @JavierAybar , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


<img src="https://media1.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 All tests passed ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 21:22 UTC, Owusu-Desmond commented on main.rb
> +end
- [ ] Please ensure that your main method presents the user with a list of options to perform, let users choose an option, If needed, ask for parameters for the option, and have a way to quit the app. The `main.rb`, the entry point (hint in this lesson https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/console_apps.md#console-app-entry-point) should be defined, this is a method called `main` that is invoked at the end of the file. This method should do and look similar to the following:

```ruby
# main.rb
def main
  app = App.new()

  response = nil

  # *Present the user with a list of options to perform.
  puts "Welcome to School Library App!\n\n"
  while response != "7"
    puts "Please choose an option by enterin a number:"
    puts "1 - List all books"
    puts "2 - List all people"
    puts "3 - Create a person"
    puts "4 - Create a book"
    puts "5 - Create a rental"
    puts "6 - List all rentals for a given person id"
    puts "7 - Exit"
    # *Lets users choose an option.
    response = gets.chomp

    case response
    when "1"
      app.list_books()
    when "2"
      app.list_people()
    when "3"
      app.create_person()
    when "4"
      app.create_book()
    when "5"
      app.create_rental()
    when "6"
      app.list_rentals_for_person_id()
    when "7"
      # *Have a way to quit the app.
      puts "Thank you for using this app!"
    end

    puts "\n"
  end
end

# 'main' method should be invoked at the end of the main.rb file, hint in this lesson https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/console_apps.md#console-app-entry-point
main()
```

2023-10-20 21:22 UTC, Owusu-Desmond commented on app/app.rb
> +  end
- [ ] All these functionalities of presenting the user with a list of options to perform, let users choose an option, and if needed, ask for parameters for the option should be implemented in your `main.rb` since it is your app entry point.

2023-10-20 23:33 UTC, JavierAybar commented
**_Hello @Owusu-Desmond!_**

_Thanks for reviewing our project! but we believe that our implementation has no problems, if you check the same [link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/console_apps.md#console-app-entry-point) that you give us, you can see the following:_


![Captura de pantalla 2023-10-20 201531](https://github.com/Rebelzob/catalog-of-my-things/assets/129561152/9542cb6a-fab6-4fa1-b952-9577d52c72bc)

_We are following that approach, and as it says there, it is a completely basic good practice._
_If we follow the approach you give us, we will have a linters error related to cyclomatic complexity because we have too many cases._

2023-10-21 00:19 UTC, Strangeal requested changes
Hi @JavierAybar and @Rebelzob, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 00:19 UTC, Strangeal commented on main.rb
> +end
- [ ] Impressive work so far. However, as suggested by the previous reviewer. The `main.rb` should present the user with a list of options to perform, let users choose an option, If needed, ask for parameters for the option, and have a way to quit the app. The `main.rb` should be the entry point of your application. Please note that this is a project requirement that should be implemented. See below for more details on the requirements:
<img width="616" alt="Screenshot 2023-10-20 at 23 54 48" src="https://github.com/Rebelzob/catalog-of-my-things/assets/107192076/ae3eb33f-1252-4403-8184-894b5f4aa519">

  - This approach not only ensures compliance with project requirements but also promotes better code organization by separating different functionalities into distinct files. This separation of concerns can significantly improve the maintainability and scalability of your codebase.
  
Happy coding! 😊🚀👨‍💻

2023-10-21 00:19 UTC, Strangeal commented on app/app.rb
> +  end
- [ ] As suggested by the previous reviewer. Kindly consider moving all functionalities of presenting the user with a list of options to perform, letting users choose an option, and if needed, asking for parameters for the option to your `main.rb` since it is your app 's entry point.

2023-10-21 00:37 UTC, JavierAybar commented
✅ _**The main.rb present the user with a list of options to perform**_
✅ **_Let users choose an option, If needed, ask for parameters for the option, and have a way to quit the app._**
✅ **_The main.rb IS the entry point of our application._**

2023-10-21 01:12 UTC, Lucas-Masaba approved these changes
# Hello @JavierAybar @diarisdiakite @Rebelzob @kambereBr  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks and tests passing :heavy_check_mark: 
- Made changes as requested by the previous reviewer :+1: 
- App is working as expected :gear: 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 08:15 UTC, Rebelzob commented on main.rb
> +end
@Strangeal @Owusu-Desmond  Thank you for your feedback on our console app. I understand that you have suggested that we create a class and incorporate it into the main method. However, I believe that this approach violates good practices and does not follow the SOLID principles.

The main method should be responsible for initializing the application and starting the main loop. It should not contain any application logic. Creating a class and incorporating it into the main method will make the code more difficult to read and maintain. It will also make it more difficult to test the code, as the test cases will need to mock out the entire class.

Additionally, the Single Responsibility Principle states that a class should only have one reason to change. Creating a class that contains both the application logic and the main loop violates this principle. A better approach would be to create a separate class for the application logic, and then call this class from the main method.

Finally, the reviewer's suggestion is inconsistent with the lesson on console apps that we were asked to follow. This lesson clearly states that the main method should be defined and should look similar to the example that we have provided.

I believe that our approach is more in line with good practices and the SOLID principles. It is also more consistent with the lesson on console apps.

2023-10-21 09:46 UTC, merged